version: 2.0
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/repo
    steps:
      - checkout

  deploy:
    filters:
      branches:
        only:
          - master
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $CLIENT_SECRET | base64 -di > ~/repo/client-secret.json
            gcloud auth activate-service-account --key-file=~/repo/client-secret.json
      - run:
          name: Deploy compojure-app to Google App Engine
          command: |
            gcloud config set project autocomplete-185121
            gcloud app deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
